version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_clientes
    restart: always
    environment:
      POSTGRES_USER: meuuser
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meuapp
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_clientes
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: meuuser
      DB_PASSWORD: minhasenha
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: meuapp
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
